5_2013211_abhinav_kumar_gaur/hello.html
=> section A 

06_2013215_Abhishek_Gusain/sample.html
Folder containing sample html file
=> Commits by Abhishek Gusain

09_2013258_Anmol_Sharma/sample.html
=> Created sample.html

38_2013412_Piyush_Mehta/sample.html
=> new directory added

58_2013540_Sunmeet_Singh
Reverts deepakuniyaliit/webPractice#53 due to invalid folder format
=> Revert "Create 58_2013540_Sunmeet_Singh"

19_2013314_Disha_Pareek/welcome.html
=> Created welcome.html

66_2014152_Mayank_Aggarwal/Hello.html
=> My First Commit

36_2013403_obaid_naseem/index.html
=> Practical 

21_2013337_Hitesh_Sachdeva/hello.html
=> web practical

22_2013339_Hrithik_Saini/hello_sir.html
=> Fullstack Web Development Practical

04_2013224_Adan_Hussain/Welcome.html
=> Full Stack Web Development  Practical

sampleprog.html
Reverts deepakuniyaliit/webPractice#109
=> Revert "Add files via upload"

28_2013343_Ishika_Jindal/welcome.html
=> FSWD practical

End Term Practice/CSECC/19_2013613_Ashish_Bisht/FSWD.html
=> First Testing

62_KETAN_PANDEY/hello.txt.txt
//practicing forking and pulling reqs
=> Hello everyone added

End Term Practice/CSECC/10_2013398_Neha_kandari/calci1.html
=> Commit success

62_KETAN_PANDEY/hello.txt.txt
Reverts deepakuniyaliit/webPractice#193
=> Revert "Hello everyone added"

End Term Practice/CSEDS/06_2013367_Kunal_Aaryen_Sinha/Q1/index.html, End Term Practice/CSEDS/06_2013367_Kunal_Aaryen_Sinha/Q1/style.css, End Term Practice/CSEDS/06_2013367_Kunal_Aaryen_Sinha/Q2/app.js, End Term Practice/CSEDS/06_2013367_Kunal_Aaryen_Sinha/Q2/index.html
=> Web Practice

End Term Practice/CSEA/17_2013259_Annu_Kumari/sample.html
=> sample.html

End Term Practice/CSEA/24_2013290_Ayush_Koul/index.html
Please let me know if this is a valid pull request and if I made any mistakes
=> Ayush Koul Pull Request

End Term Practice/CSEB/23_2013349_JyotiBisht/index.html
=> created new file for practice

End Term Practice/CSED/52_2013527_Sidhant_Bidaliya/hello.html
=> fswd practical practice

End Term Practice/CSEB/03_2013220_Abhishek_Sarewar/QN1/demo1.txt
=> sample test

End Term Practice/CSEE/34_2013503_Shivangi_Bisht/helloworld.php
=> helloworld.php

End Term Practice/CSEE/51_2013563_Ujjawal_Varshney/mathpow.html
=> Test changes

End Term Practice/CSEDS/40_2013664_Sunny_Goswami/index.html
=> Update: Added DS_40
